# Generated by Django 4.0.3 on 2022-04-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contnet',
            new_name='content',
        ),
    ]
