# Generated by Django 4.0.4 on 2022-04-30 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_contnet_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
